[2025-02-18T18:21:01.648+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.transform manual__2025-02-18T18:20:56.895306+00:00 [queued]>
[2025-02-18T18:21:01.664+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.transform manual__2025-02-18T18:20:56.895306+00:00 [queued]>
[2025-02-18T18:21:01.665+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-18T18:21:01.667+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-02-18T18:21:01.667+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-18T18:21:01.694+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): transform> on 2025-02-18 18:20:56.895306+00:00
[2025-02-18T18:21:01.701+0000] {standard_task_runner.py:55} INFO - Started process 337 to run task
[2025-02-18T18:21:01.705+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform', 'manual__2025-02-18T18:20:56.895306+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxb916k9j']
[2025-02-18T18:21:01.708+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask transform
[2025-02-18T18:21:01.732+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T18:21:01.810+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_pipeline.transform manual__2025-02-18T18:20:56.895306+00:00 [running]> on host 25ff48d7fca5
[2025-02-18T18:21:01.910+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pipeline
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2025-02-18T18:20:56.895306+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-18T18:20:56.895306+00:00
[2025-02-18T18:21:01.912+0000] {logging_mixin.py:137} INFO - üîç Ejecutando el comando: docker exec etl-pipeline-spark-1 /opt/spark/bin/spark-submit /scripts/spark_etl.py
[2025-02-18T18:21:02.024+0000] {logging_mixin.py:137} INFO - ‚ùå ERROR en Spark ETL:
[2025-02-18T18:21:02.026+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 22, in spark_etl
    shell=True  # Especificamos shell=True porque estamos ejecutando un comando de bash
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker exec etl-pipeline-spark-1 /opt/spark/bin/spark-submit /scripts/spark_etl.py' returned non-zero exit status 126.
[2025-02-18T18:21:02.047+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=transform, execution_date=20250218T182056, start_date=20250218T182101, end_date=20250218T182102
[2025-02-18T18:21:02.077+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task transform (Command 'docker exec etl-pipeline-spark-1 /opt/spark/bin/spark-submit /scripts/spark_etl.py' returned non-zero exit status 126.; 337)
[2025-02-18T18:21:02.120+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-18T18:21:02.179+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
